### ISSUE TITLE
"ServiceTier [bc] not found" in Release Pipeline BC21

### ISSUE THREAD

**Issue by FabioC34** [HodorNV/ALOps-External-Deployer#5]
Hi,
I disinstalled 1.38 and installed new version 1.41 for the problems related to BC21
I tried to publish again, but unfortunately I get another error, this time everything seems ok in Powershell, the release pipeline terminate with ok.
But the status in P2508 is “Failed”, and the error says “ServiceTier [bc] not found.”. I checked the Event Viewer on Service Server, and there is one information line about AlOpsExternalDeployer with the following log:

![image](https://user-images.githubusercontent.com/57533883/202241346-9da15bfc-9bf4-4e16-abde-8d6a45e3ab43.png)

My ServerInstance is named BC210, and of course I configured AlOps External Deployer with this PowerShell line:
New-ALOpsExternalDeployer -ServerInstance BC210 (and everything seemed ok, with also the restart of BC210 service), here below the installation log:

![image](https://user-images.githubusercontent.com/57533883/202241146-0d87f731-a917-49d1-a60a-e36d1d021097.png)

Thank you
Fabio

**Comment by CBIZGIT** [comment]
Have the same issue as Fabio (updating from initial service install for BC200 to new additional service BC210)
